### ISSUE TITLE
Deployment to AWS Beanstalk

### ISSUE THREAD

**Issue by TiesdeKok** [fhboswell/Guardian-face-recognition-API#1]
Hi there!

While Googling on how to get DLIB (i.e. the face recognition package) running on AWS Elastic Beanstalk I bumped into your repository.

It seems close to what I am trying to accomplish but I am having troubles deploying it using the EB CLI interface.

What are the steps that you do to actually deploy this to AWS Beanstalk?

Many thanks!

**Comment by fhboswell** [comment]
I deploy to AWS through docker.

I followed this [guide](https://docs.docker.com/get-started/part6/#deploy-your-app-on-a-cloud-provider):
https://docs.docker.com/get-started/part6/#deploy-your-app-on-a-cloud-provider

the pre built docker image is here: fhboswell/face-recognition
`docker pull fhboswell/face-recognition`

However you can build your own using the docker CLI

The docker image is large and sometimes fails to load to the instance, in the case that happens just try again, it will work.

Good luck!

**Comment by TiesdeKok** [comment]
Great, that is all I needed to know. Thanks!

**Comment by TiesdeKok** [comment]
Slight update, got everything to work!

I did have to add a `Dockerrun.aws.json` file for it to work:

````
{
  "AWSEBDockerrunVersion": "1",
  "Image": {
    "Name": "tiesdekok/<dockerimage>",
    "Update": "true"
  },
  "Ports": [
    {
      "ContainerPort": "80"
    }
  ],
  "Logging": "/var/log/"
}
````

With only the `Dockerfile` the deployment would crash. Maybe this is just something for my use-case but  I figured to share anyways!
